# =============================================================================
# Compile Design
# =============================================================================
# Author  : Gedeon Nyengele
# Date    : April 5, 2020
# =============================================================================

name: compile_design

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------
commands:
  - bash run.sh


# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------

parameters:
  ARM_IP_DIR: undefined
  AHA_IP_DIR: undefined
  CGRA_RD_WS: 1
  soc_only: undefined
