# =============================================================================
# Compile Design
# =============================================================================
# Author  : Gedeon Nyengele
# Date    : April 5, 2020
# =============================================================================

name: compile_design

# -----------------------------------------------------------------------------
# Inputs
# -----------------------------------------------------------------------------
inputs:
  - design.v

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------
commands:
  - bash run.sh


# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------

parameters:
  ARM_IP_DIR: undefined
  AHA_IP_DIR: undefined
  soc_only: undefined
  TLX_FWD_DATA_LO_WIDTH: undefined
  TLX_REV_DATA_LO_WIDTH: undefined
  IMPL_VIEW: undefined
  TEST_VIEW: undefined
  PROCESS: undefined
  SIMULATOR: undefined
  INCLUDE_XGCD: undefined
