# =============================================================================
# Run Test
# =============================================================================
# Author  : Kalhan Koul
# Date    : February 7, 2021
# =============================================================================

name: ptpx


# -----------------------------------------------------------------------------
# Inputs
# -----------------------------------------------------------------------------
inputs:
  - run.saif 

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------
commands:
  - bash run.sh


# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------

parameters:
  TEST_NAME: undefined
  design_name: undefined
  strip_path: undefined
  GATE_LEVEL_DIR: undefined
  clock_period: undefined
  design_name: undefined
