# =============================================================================
# Compile Design
# =============================================================================
# Author  : Gedeon Nyengele
# Date    : April 5, 2020
# =============================================================================

name: amber

# -----------------------------------------------------------------------------
# Inputs
# -----------------------------------------------------------------------------
outputs:
  - design.v





