# =============================================================================
# Gatelevel Power Analysis
# =============================================================================

name: gatelevel_power_analysis

# -----------------------------------------------------------------------------
# Inputs
# -----------------------------------------------------------------------------
inputs:
  - run.fsdb
  # - run.saif

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------
commands:
  - bash run.sh


