# =============================================================================
# XGCD RTL
# =============================================================================
# Author  : Gedeon Nyengele
# Date    : Oct 5, 2022
# =============================================================================

name: xgcd

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------
commands:
  - bash run.sh
  
# -----------------------------------------------------------------------------
# Inputs
# -----------------------------------------------------------------------------
outputs:
  - xgcd_design.v
