//   Ordt 190617.01 autogenerated file
//   Input: platform_ctrl.rdl
//   Parms: ./ordt/params.txt
//   Date: Wed May 06 18:25:11 PDT 2020
//

//
//---------- module AhaPlatformCtrlAddrMap_jrdl_decode
//
module AhaPlatformCtrlAddrMap_jrdl_decode
(
  clk,
  reset,
  h2d_pio_dec_address,
  h2d_pio_dec_write_data,
  h2d_pio_dec_write_enable,
  h2d_pio_dec_write,
  h2d_pio_dec_read,
  l2d_ID_REG_r,
  l2d_PAD_STRENGTH_CTRL_REG_r,
  l2d_SYS_CLK_SELECT_REG_r,
  l2d_DMA0_PCLK_SELECT_REG_r,
  l2d_DMA1_PCLK_SELECT_REG_r,
  l2d_TLX_FWD_CLK_SELECT_REG_r,
  l2d_CGRA_CLK_SELECT_REG_r,
  l2d_TIMER0_CLK_SELECT_REG_r,
  l2d_TIMER1_CLK_SELECT_REG_r,
  l2d_UART0_CLK_SELECT_REG_r,
  l2d_UART1_CLK_SELECT_REG_r,
  l2d_WDOG_CLK_SELECT_REG_r,
  l2d_CLK_GATE_EN_REG_r,
  l2d_SYS_RESET_PROP_REG_r,
  l2d_RESET_REQ_REG_r,
  l2d_RESET_ACK_REG_r,
  l2d_SYS_TICK_CONFIG_REG_r,
  l2d_SYS_RESET_AGGR_REG_r,

  d2h_dec_pio_read_data,
  d2h_dec_pio_ack,
  d2h_dec_pio_nack,
  d2l_ID_REG_w,
  d2l_ID_REG_w_enable,
  d2l_ID_REG_we,
  d2l_ID_REG_re,
  d2l_PAD_STRENGTH_CTRL_REG_w,
  d2l_PAD_STRENGTH_CTRL_REG_w_enable,
  d2l_PAD_STRENGTH_CTRL_REG_we,
  d2l_PAD_STRENGTH_CTRL_REG_re,
  d2l_SYS_CLK_SELECT_REG_w,
  d2l_SYS_CLK_SELECT_REG_w_enable,
  d2l_SYS_CLK_SELECT_REG_we,
  d2l_SYS_CLK_SELECT_REG_re,
  d2l_DMA0_PCLK_SELECT_REG_w,
  d2l_DMA0_PCLK_SELECT_REG_w_enable,
  d2l_DMA0_PCLK_SELECT_REG_we,
  d2l_DMA0_PCLK_SELECT_REG_re,
  d2l_DMA1_PCLK_SELECT_REG_w,
  d2l_DMA1_PCLK_SELECT_REG_w_enable,
  d2l_DMA1_PCLK_SELECT_REG_we,
  d2l_DMA1_PCLK_SELECT_REG_re,
  d2l_TLX_FWD_CLK_SELECT_REG_w,
  d2l_TLX_FWD_CLK_SELECT_REG_w_enable,
  d2l_TLX_FWD_CLK_SELECT_REG_we,
  d2l_TLX_FWD_CLK_SELECT_REG_re,
  d2l_CGRA_CLK_SELECT_REG_w,
  d2l_CGRA_CLK_SELECT_REG_w_enable,
  d2l_CGRA_CLK_SELECT_REG_we,
  d2l_CGRA_CLK_SELECT_REG_re,
  d2l_TIMER0_CLK_SELECT_REG_w,
  d2l_TIMER0_CLK_SELECT_REG_w_enable,
  d2l_TIMER0_CLK_SELECT_REG_we,
  d2l_TIMER0_CLK_SELECT_REG_re,
  d2l_TIMER1_CLK_SELECT_REG_w,
  d2l_TIMER1_CLK_SELECT_REG_w_enable,
  d2l_TIMER1_CLK_SELECT_REG_we,
  d2l_TIMER1_CLK_SELECT_REG_re,
  d2l_UART0_CLK_SELECT_REG_w,
  d2l_UART0_CLK_SELECT_REG_w_enable,
  d2l_UART0_CLK_SELECT_REG_we,
  d2l_UART0_CLK_SELECT_REG_re,
  d2l_UART1_CLK_SELECT_REG_w,
  d2l_UART1_CLK_SELECT_REG_w_enable,
  d2l_UART1_CLK_SELECT_REG_we,
  d2l_UART1_CLK_SELECT_REG_re,
  d2l_WDOG_CLK_SELECT_REG_w,
  d2l_WDOG_CLK_SELECT_REG_w_enable,
  d2l_WDOG_CLK_SELECT_REG_we,
  d2l_WDOG_CLK_SELECT_REG_re,
  d2l_CLK_GATE_EN_REG_w,
  d2l_CLK_GATE_EN_REG_w_enable,
  d2l_CLK_GATE_EN_REG_we,
  d2l_CLK_GATE_EN_REG_re,
  d2l_SYS_RESET_PROP_REG_w,
  d2l_SYS_RESET_PROP_REG_w_enable,
  d2l_SYS_RESET_PROP_REG_we,
  d2l_SYS_RESET_PROP_REG_re,
  d2l_RESET_REQ_REG_w,
  d2l_RESET_REQ_REG_w_enable,
  d2l_RESET_REQ_REG_we,
  d2l_RESET_REQ_REG_re,
  d2l_RESET_ACK_REG_w,
  d2l_RESET_ACK_REG_w_enable,
  d2l_RESET_ACK_REG_we,
  d2l_RESET_ACK_REG_re,
  d2l_SYS_TICK_CONFIG_REG_w,
  d2l_SYS_TICK_CONFIG_REG_w_enable,
  d2l_SYS_TICK_CONFIG_REG_we,
  d2l_SYS_TICK_CONFIG_REG_re,
  d2l_SYS_RESET_AGGR_REG_w,
  d2l_SYS_RESET_AGGR_REG_w_enable,
  d2l_SYS_RESET_AGGR_REG_we,
  d2l_SYS_RESET_AGGR_REG_re );

  //------- inputs
  input    clk;
  input    reset;
  input     [6:2] h2d_pio_dec_address;
  input     [31:0] h2d_pio_dec_write_data;
  input     [3:0] h2d_pio_dec_write_enable;
  input    h2d_pio_dec_write;
  input    h2d_pio_dec_read;
  input     [31:0] l2d_ID_REG_r;
  input     [31:0] l2d_PAD_STRENGTH_CTRL_REG_r;
  input     [31:0] l2d_SYS_CLK_SELECT_REG_r;
  input     [31:0] l2d_DMA0_PCLK_SELECT_REG_r;
  input     [31:0] l2d_DMA1_PCLK_SELECT_REG_r;
  input     [31:0] l2d_TLX_FWD_CLK_SELECT_REG_r;
  input     [31:0] l2d_CGRA_CLK_SELECT_REG_r;
  input     [31:0] l2d_TIMER0_CLK_SELECT_REG_r;
  input     [31:0] l2d_TIMER1_CLK_SELECT_REG_r;
  input     [31:0] l2d_UART0_CLK_SELECT_REG_r;
  input     [31:0] l2d_UART1_CLK_SELECT_REG_r;
  input     [31:0] l2d_WDOG_CLK_SELECT_REG_r;
  input     [31:0] l2d_CLK_GATE_EN_REG_r;
  input     [31:0] l2d_SYS_RESET_PROP_REG_r;
  input     [31:0] l2d_RESET_REQ_REG_r;
  input     [31:0] l2d_RESET_ACK_REG_r;
  input     [31:0] l2d_SYS_TICK_CONFIG_REG_r;
  input     [31:0] l2d_SYS_RESET_AGGR_REG_r;

  //------- outputs
  output     [31:0] d2h_dec_pio_read_data;
  output    d2h_dec_pio_ack;
  output    d2h_dec_pio_nack;
  output     [31:0] d2l_ID_REG_w;
  output     [31:0] d2l_ID_REG_w_enable;
  output    d2l_ID_REG_we;
  output    d2l_ID_REG_re;
  output     [31:0] d2l_PAD_STRENGTH_CTRL_REG_w;
  output     [31:0] d2l_PAD_STRENGTH_CTRL_REG_w_enable;
  output    d2l_PAD_STRENGTH_CTRL_REG_we;
  output    d2l_PAD_STRENGTH_CTRL_REG_re;
  output     [31:0] d2l_SYS_CLK_SELECT_REG_w;
  output     [31:0] d2l_SYS_CLK_SELECT_REG_w_enable;
  output    d2l_SYS_CLK_SELECT_REG_we;
  output    d2l_SYS_CLK_SELECT_REG_re;
  output     [31:0] d2l_DMA0_PCLK_SELECT_REG_w;
  output     [31:0] d2l_DMA0_PCLK_SELECT_REG_w_enable;
  output    d2l_DMA0_PCLK_SELECT_REG_we;
  output    d2l_DMA0_PCLK_SELECT_REG_re;
  output     [31:0] d2l_DMA1_PCLK_SELECT_REG_w;
  output     [31:0] d2l_DMA1_PCLK_SELECT_REG_w_enable;
  output    d2l_DMA1_PCLK_SELECT_REG_we;
  output    d2l_DMA1_PCLK_SELECT_REG_re;
  output     [31:0] d2l_TLX_FWD_CLK_SELECT_REG_w;
  output     [31:0] d2l_TLX_FWD_CLK_SELECT_REG_w_enable;
  output    d2l_TLX_FWD_CLK_SELECT_REG_we;
  output    d2l_TLX_FWD_CLK_SELECT_REG_re;
  output     [31:0] d2l_CGRA_CLK_SELECT_REG_w;
  output     [31:0] d2l_CGRA_CLK_SELECT_REG_w_enable;
  output    d2l_CGRA_CLK_SELECT_REG_we;
  output    d2l_CGRA_CLK_SELECT_REG_re;
  output     [31:0] d2l_TIMER0_CLK_SELECT_REG_w;
  output     [31:0] d2l_TIMER0_CLK_SELECT_REG_w_enable;
  output    d2l_TIMER0_CLK_SELECT_REG_we;
  output    d2l_TIMER0_CLK_SELECT_REG_re;
  output     [31:0] d2l_TIMER1_CLK_SELECT_REG_w;
  output     [31:0] d2l_TIMER1_CLK_SELECT_REG_w_enable;
  output    d2l_TIMER1_CLK_SELECT_REG_we;
  output    d2l_TIMER1_CLK_SELECT_REG_re;
  output     [31:0] d2l_UART0_CLK_SELECT_REG_w;
  output     [31:0] d2l_UART0_CLK_SELECT_REG_w_enable;
  output    d2l_UART0_CLK_SELECT_REG_we;
  output    d2l_UART0_CLK_SELECT_REG_re;
  output     [31:0] d2l_UART1_CLK_SELECT_REG_w;
  output     [31:0] d2l_UART1_CLK_SELECT_REG_w_enable;
  output    d2l_UART1_CLK_SELECT_REG_we;
  output    d2l_UART1_CLK_SELECT_REG_re;
  output     [31:0] d2l_WDOG_CLK_SELECT_REG_w;
  output     [31:0] d2l_WDOG_CLK_SELECT_REG_w_enable;
  output    d2l_WDOG_CLK_SELECT_REG_we;
  output    d2l_WDOG_CLK_SELECT_REG_re;
  output     [31:0] d2l_CLK_GATE_EN_REG_w;
  output     [31:0] d2l_CLK_GATE_EN_REG_w_enable;
  output    d2l_CLK_GATE_EN_REG_we;
  output    d2l_CLK_GATE_EN_REG_re;
  output     [31:0] d2l_SYS_RESET_PROP_REG_w;
  output     [31:0] d2l_SYS_RESET_PROP_REG_w_enable;
  output    d2l_SYS_RESET_PROP_REG_we;
  output    d2l_SYS_RESET_PROP_REG_re;
  output     [31:0] d2l_RESET_REQ_REG_w;
  output     [31:0] d2l_RESET_REQ_REG_w_enable;
  output    d2l_RESET_REQ_REG_we;
  output    d2l_RESET_REQ_REG_re;
  output     [31:0] d2l_RESET_ACK_REG_w;
  output     [31:0] d2l_RESET_ACK_REG_w_enable;
  output    d2l_RESET_ACK_REG_we;
  output    d2l_RESET_ACK_REG_re;
  output     [31:0] d2l_SYS_TICK_CONFIG_REG_w;
  output     [31:0] d2l_SYS_TICK_CONFIG_REG_w_enable;
  output    d2l_SYS_TICK_CONFIG_REG_we;
  output    d2l_SYS_TICK_CONFIG_REG_re;
  output     [31:0] d2l_SYS_RESET_AGGR_REG_w;
  output     [31:0] d2l_SYS_RESET_AGGR_REG_w_enable;
  output    d2l_SYS_RESET_AGGR_REG_we;
  output    d2l_SYS_RESET_AGGR_REG_re;


  //------- wire defines
  wire   [6:2] pio_dec_address;
  wire   [31:0] pio_dec_write_data;
  wire   [3:0] pio_dec_write_enable;
  wire  pio_dec_read;
  wire  pio_dec_write;

  //------- reg defines
  reg   [31:0] d2l_ID_REG_w;
  reg   [31:0] d2l_ID_REG_w_enable;
  reg  d2l_ID_REG_we;
  reg  d2l_ID_REG_re;
  reg   [31:0] d2l_PAD_STRENGTH_CTRL_REG_w;
  reg   [31:0] d2l_PAD_STRENGTH_CTRL_REG_w_enable;
  reg  d2l_PAD_STRENGTH_CTRL_REG_we;
  reg  d2l_PAD_STRENGTH_CTRL_REG_re;
  reg   [31:0] d2l_SYS_CLK_SELECT_REG_w;
  reg   [31:0] d2l_SYS_CLK_SELECT_REG_w_enable;
  reg  d2l_SYS_CLK_SELECT_REG_we;
  reg  d2l_SYS_CLK_SELECT_REG_re;
  reg   [31:0] d2l_DMA0_PCLK_SELECT_REG_w;
  reg   [31:0] d2l_DMA0_PCLK_SELECT_REG_w_enable;
  reg  d2l_DMA0_PCLK_SELECT_REG_we;
  reg  d2l_DMA0_PCLK_SELECT_REG_re;
  reg   [31:0] d2l_DMA1_PCLK_SELECT_REG_w;
  reg   [31:0] d2l_DMA1_PCLK_SELECT_REG_w_enable;
  reg  d2l_DMA1_PCLK_SELECT_REG_we;
  reg  d2l_DMA1_PCLK_SELECT_REG_re;
  reg   [31:0] d2l_TLX_FWD_CLK_SELECT_REG_w;
  reg   [31:0] d2l_TLX_FWD_CLK_SELECT_REG_w_enable;
  reg  d2l_TLX_FWD_CLK_SELECT_REG_we;
  reg  d2l_TLX_FWD_CLK_SELECT_REG_re;
  reg   [31:0] d2l_CGRA_CLK_SELECT_REG_w;
  reg   [31:0] d2l_CGRA_CLK_SELECT_REG_w_enable;
  reg  d2l_CGRA_CLK_SELECT_REG_we;
  reg  d2l_CGRA_CLK_SELECT_REG_re;
  reg   [31:0] d2l_TIMER0_CLK_SELECT_REG_w;
  reg   [31:0] d2l_TIMER0_CLK_SELECT_REG_w_enable;
  reg  d2l_TIMER0_CLK_SELECT_REG_we;
  reg  d2l_TIMER0_CLK_SELECT_REG_re;
  reg   [31:0] d2l_TIMER1_CLK_SELECT_REG_w;
  reg   [31:0] d2l_TIMER1_CLK_SELECT_REG_w_enable;
  reg  d2l_TIMER1_CLK_SELECT_REG_we;
  reg  d2l_TIMER1_CLK_SELECT_REG_re;
  reg   [31:0] d2l_UART0_CLK_SELECT_REG_w;
  reg   [31:0] d2l_UART0_CLK_SELECT_REG_w_enable;
  reg  d2l_UART0_CLK_SELECT_REG_we;
  reg  d2l_UART0_CLK_SELECT_REG_re;
  reg   [31:0] d2l_UART1_CLK_SELECT_REG_w;
  reg   [31:0] d2l_UART1_CLK_SELECT_REG_w_enable;
  reg  d2l_UART1_CLK_SELECT_REG_we;
  reg  d2l_UART1_CLK_SELECT_REG_re;
  reg   [31:0] d2l_WDOG_CLK_SELECT_REG_w;
  reg   [31:0] d2l_WDOG_CLK_SELECT_REG_w_enable;
  reg  d2l_WDOG_CLK_SELECT_REG_we;
  reg  d2l_WDOG_CLK_SELECT_REG_re;
  reg   [31:0] d2l_CLK_GATE_EN_REG_w;
  reg   [31:0] d2l_CLK_GATE_EN_REG_w_enable;
  reg  d2l_CLK_GATE_EN_REG_we;
  reg  d2l_CLK_GATE_EN_REG_re;
  reg   [31:0] d2l_SYS_RESET_PROP_REG_w;
  reg   [31:0] d2l_SYS_RESET_PROP_REG_w_enable;
  reg  d2l_SYS_RESET_PROP_REG_we;
  reg  d2l_SYS_RESET_PROP_REG_re;
  reg   [31:0] d2l_RESET_REQ_REG_w;
  reg   [31:0] d2l_RESET_REQ_REG_w_enable;
  reg  d2l_RESET_REQ_REG_we;
  reg  d2l_RESET_REQ_REG_re;
  reg   [31:0] d2l_RESET_ACK_REG_w;
  reg   [31:0] d2l_RESET_ACK_REG_w_enable;
  reg  d2l_RESET_ACK_REG_we;
  reg  d2l_RESET_ACK_REG_re;
  reg   [31:0] d2l_SYS_TICK_CONFIG_REG_w;
  reg   [31:0] d2l_SYS_TICK_CONFIG_REG_w_enable;
  reg  d2l_SYS_TICK_CONFIG_REG_we;
  reg  d2l_SYS_TICK_CONFIG_REG_re;
  reg   [31:0] d2l_SYS_RESET_AGGR_REG_w;
  reg   [31:0] d2l_SYS_RESET_AGGR_REG_w_enable;
  reg  d2l_SYS_RESET_AGGR_REG_we;
  reg  d2l_SYS_RESET_AGGR_REG_re;
  reg  pio_write_active;
  reg  pio_read_active;
  reg   [6:2] pio_dec_address_d1;
  reg   [31:0] pio_dec_write_data_d1;
  reg   [3:0] pio_dec_write_enable_d1;
  reg   [31:0] pio_dec_write_enable_full;
  reg   [31:0] dec_pio_read_data;
  reg   [31:0] dec_pio_read_data_d1;
  reg  dec_pio_ack;
  reg  dec_pio_nack;
  reg  dec_pio_ack_next;
  reg  dec_pio_nack_next;
  reg  pio_internal_ack;
  reg  pio_internal_nack;
  reg  pio_external_ack;
  reg  pio_external_nack;
  reg  pio_external_ack_next;
  reg  pio_external_nack_next;
  reg  pio_no_acks;
  reg  pio_activate_write;
  reg  pio_activate_read;
  reg   [31:0] dec_pio_read_data_next;
  reg  external_transaction_active;


  //------- assigns
  assign  pio_dec_address = h2d_pio_dec_address;
  assign  pio_dec_write_data = h2d_pio_dec_write_data;
  assign  pio_dec_write_enable = h2d_pio_dec_write_enable;
  assign  pio_dec_read = h2d_pio_dec_read;
  assign  pio_dec_write = h2d_pio_dec_write;
  assign  d2h_dec_pio_read_data = dec_pio_read_data;
  assign  d2h_dec_pio_ack = dec_pio_ack;
  assign  d2h_dec_pio_nack = dec_pio_nack;

  //------- combinatorial assigns for pio read data
  always @ (*) begin
    dec_pio_read_data = dec_pio_read_data_d1;
  end

  //------- reg assigns for pio read data
  always @ (posedge clk or posedge reset) begin
    if (reset) begin
      dec_pio_read_data_d1 <= #1  32'b0;
    end
    else begin
      dec_pio_read_data_d1 <= #1 dec_pio_read_data_next;
    end
  end

  //------- reg assigns for pio i/f
  always @ (posedge clk or posedge reset) begin
    if (reset) begin
      pio_write_active <= #1  1'b0;
      pio_read_active <= #1  1'b0;
    end
    else begin
      pio_write_active <= #1  pio_write_active ? pio_no_acks : pio_activate_write;
      pio_read_active <= #1  pio_read_active ? pio_no_acks : pio_activate_read;
      pio_dec_address_d1 <= #1   pio_dec_address;
      pio_dec_write_data_d1 <= #1  pio_dec_write_data;
      pio_dec_write_enable_d1 <= #1  pio_dec_write_enable;
    end
  end

  //------- combinatorial assigns for pio ack/nack
  always @ (*) begin
    pio_internal_nack = (pio_read_active | pio_write_active) & ~pio_internal_ack & ~external_transaction_active;
    dec_pio_ack_next = (pio_internal_ack | (pio_external_ack_next & external_transaction_active));
    dec_pio_nack_next = (pio_internal_nack | (pio_external_nack_next & external_transaction_active));
    pio_no_acks = ~(dec_pio_ack | dec_pio_nack | pio_external_ack | pio_external_nack);
    pio_activate_write = (pio_dec_write & ~(dec_pio_ack | dec_pio_nack));
    pio_activate_read = (pio_dec_read & ~(dec_pio_ack | dec_pio_nack));
  end

  //------- reg assigns for pio ack/nack
  always @ (posedge clk or posedge reset) begin
    if (reset) begin
      dec_pio_ack <= #1 1'b0;
      dec_pio_nack <= #1 1'b0;
      pio_external_ack <= #1  1'b0;
      pio_external_nack <= #1  1'b0;
    end
    else begin
      dec_pio_ack <= #1 dec_pio_ack ? 1'b0 : dec_pio_ack_next;
      dec_pio_nack <= #1 dec_pio_nack ? 1'b0 : dec_pio_nack_next;
      pio_external_ack <= #1 pio_external_ack_next;
      pio_external_nack <= #1 pio_external_nack_next;
    end
  end


  //------- address decode
  always @ (*) begin
    pio_internal_ack = 1'b0;
    external_transaction_active = 1'b0;
    pio_external_ack_next = 1'b0;
    pio_external_nack_next = 1'b0;
    dec_pio_read_data_next = 32'b0;
    pio_dec_write_enable_full = 32'd0;
    if (pio_dec_write_enable_d1[0]) pio_dec_write_enable_full [7:0]  = 8'hff;
    if (pio_dec_write_enable_d1[1]) pio_dec_write_enable_full [15:8]  = 8'hff;
    if (pio_dec_write_enable_d1[2]) pio_dec_write_enable_full [23:16]  = 8'hff;
    if (pio_dec_write_enable_d1[3]) pio_dec_write_enable_full [31:24]  = 8'hff;

    d2l_ID_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ID_REG_we = 1'b0;
    d2l_ID_REG_re = 1'b0;
    d2l_ID_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_PAD_STRENGTH_CTRL_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_PAD_STRENGTH_CTRL_REG_we = 1'b0;
    d2l_PAD_STRENGTH_CTRL_REG_re = 1'b0;
    d2l_PAD_STRENGTH_CTRL_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_SYS_CLK_SELECT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_SYS_CLK_SELECT_REG_we = 1'b0;
    d2l_SYS_CLK_SELECT_REG_re = 1'b0;
    d2l_SYS_CLK_SELECT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_DMA0_PCLK_SELECT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_DMA0_PCLK_SELECT_REG_we = 1'b0;
    d2l_DMA0_PCLK_SELECT_REG_re = 1'b0;
    d2l_DMA0_PCLK_SELECT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_DMA1_PCLK_SELECT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_DMA1_PCLK_SELECT_REG_we = 1'b0;
    d2l_DMA1_PCLK_SELECT_REG_re = 1'b0;
    d2l_DMA1_PCLK_SELECT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_TLX_FWD_CLK_SELECT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_TLX_FWD_CLK_SELECT_REG_we = 1'b0;
    d2l_TLX_FWD_CLK_SELECT_REG_re = 1'b0;
    d2l_TLX_FWD_CLK_SELECT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_CGRA_CLK_SELECT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_CGRA_CLK_SELECT_REG_we = 1'b0;
    d2l_CGRA_CLK_SELECT_REG_re = 1'b0;
    d2l_CGRA_CLK_SELECT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_TIMER0_CLK_SELECT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_TIMER0_CLK_SELECT_REG_we = 1'b0;
    d2l_TIMER0_CLK_SELECT_REG_re = 1'b0;
    d2l_TIMER0_CLK_SELECT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_TIMER1_CLK_SELECT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_TIMER1_CLK_SELECT_REG_we = 1'b0;
    d2l_TIMER1_CLK_SELECT_REG_re = 1'b0;
    d2l_TIMER1_CLK_SELECT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_UART0_CLK_SELECT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_UART0_CLK_SELECT_REG_we = 1'b0;
    d2l_UART0_CLK_SELECT_REG_re = 1'b0;
    d2l_UART0_CLK_SELECT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_UART1_CLK_SELECT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_UART1_CLK_SELECT_REG_we = 1'b0;
    d2l_UART1_CLK_SELECT_REG_re = 1'b0;
    d2l_UART1_CLK_SELECT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_WDOG_CLK_SELECT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_WDOG_CLK_SELECT_REG_we = 1'b0;
    d2l_WDOG_CLK_SELECT_REG_re = 1'b0;
    d2l_WDOG_CLK_SELECT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_CLK_GATE_EN_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_CLK_GATE_EN_REG_we = 1'b0;
    d2l_CLK_GATE_EN_REG_re = 1'b0;
    d2l_CLK_GATE_EN_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_SYS_RESET_PROP_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_SYS_RESET_PROP_REG_we = 1'b0;
    d2l_SYS_RESET_PROP_REG_re = 1'b0;
    d2l_SYS_RESET_PROP_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_RESET_REQ_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_RESET_REQ_REG_we = 1'b0;
    d2l_RESET_REQ_REG_re = 1'b0;
    d2l_RESET_REQ_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_RESET_ACK_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_RESET_ACK_REG_we = 1'b0;
    d2l_RESET_ACK_REG_re = 1'b0;
    d2l_RESET_ACK_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_SYS_TICK_CONFIG_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_SYS_TICK_CONFIG_REG_we = 1'b0;
    d2l_SYS_TICK_CONFIG_REG_re = 1'b0;
    d2l_SYS_TICK_CONFIG_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_SYS_RESET_AGGR_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_SYS_RESET_AGGR_REG_we = 1'b0;
    d2l_SYS_RESET_AGGR_REG_re = 1'b0;
    d2l_SYS_RESET_AGGR_REG_w_enable = pio_dec_write_enable_full  [31:0] ;

    casez(pio_dec_address_d1)
    //  Register: ID_REG     Address: 0x0     External: false
    5'b00000:
      begin
        d2l_ID_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_ID_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_ID_REG_r;
      end
    //  Register: PAD_STRENGTH_CTRL_REG     Address: 0x4     External: false
    5'b00001:
      begin
        d2l_PAD_STRENGTH_CTRL_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_PAD_STRENGTH_CTRL_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_PAD_STRENGTH_CTRL_REG_r;
      end
    //  Register: SYS_CLK_SELECT_REG     Address: 0x8     External: false
    5'b00010:
      begin
        d2l_SYS_CLK_SELECT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_SYS_CLK_SELECT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_SYS_CLK_SELECT_REG_r;
      end
    //  Register: DMA0_PCLK_SELECT_REG     Address: 0x14     External: false
    5'b00101:
      begin
        d2l_DMA0_PCLK_SELECT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_DMA0_PCLK_SELECT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_DMA0_PCLK_SELECT_REG_r;
      end
    //  Register: DMA1_PCLK_SELECT_REG     Address: 0x18     External: false
    5'b00110:
      begin
        d2l_DMA1_PCLK_SELECT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_DMA1_PCLK_SELECT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_DMA1_PCLK_SELECT_REG_r;
      end
    //  Register: TLX_FWD_CLK_SELECT_REG     Address: 0x20     External: false
    5'b01000:
      begin
        d2l_TLX_FWD_CLK_SELECT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_TLX_FWD_CLK_SELECT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_TLX_FWD_CLK_SELECT_REG_r;
      end
    //  Register: CGRA_CLK_SELECT_REG     Address: 0x28     External: false
    5'b01010:
      begin
        d2l_CGRA_CLK_SELECT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_CGRA_CLK_SELECT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_CGRA_CLK_SELECT_REG_r;
      end
    //  Register: TIMER0_CLK_SELECT_REG     Address: 0x30     External: false
    5'b01100:
      begin
        d2l_TIMER0_CLK_SELECT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_TIMER0_CLK_SELECT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_TIMER0_CLK_SELECT_REG_r;
      end
    //  Register: TIMER1_CLK_SELECT_REG     Address: 0x34     External: false
    5'b01101:
      begin
        d2l_TIMER1_CLK_SELECT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_TIMER1_CLK_SELECT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_TIMER1_CLK_SELECT_REG_r;
      end
    //  Register: UART0_CLK_SELECT_REG     Address: 0x38     External: false
    5'b01110:
      begin
        d2l_UART0_CLK_SELECT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_UART0_CLK_SELECT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_UART0_CLK_SELECT_REG_r;
      end
    //  Register: UART1_CLK_SELECT_REG     Address: 0x3c     External: false
    5'b01111:
      begin
        d2l_UART1_CLK_SELECT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_UART1_CLK_SELECT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_UART1_CLK_SELECT_REG_r;
      end
    //  Register: WDOG_CLK_SELECT_REG     Address: 0x40     External: false
    5'b10000:
      begin
        d2l_WDOG_CLK_SELECT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_WDOG_CLK_SELECT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_WDOG_CLK_SELECT_REG_r;
      end
    //  Register: CLK_GATE_EN_REG     Address: 0x44     External: false
    5'b10001:
      begin
        d2l_CLK_GATE_EN_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_CLK_GATE_EN_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_CLK_GATE_EN_REG_r;
      end
    //  Register: SYS_RESET_PROP_REG     Address: 0x48     External: false
    5'b10010:
      begin
        d2l_SYS_RESET_PROP_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_SYS_RESET_PROP_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_SYS_RESET_PROP_REG_r;
      end
    //  Register: RESET_REQ_REG     Address: 0x4c     External: false
    5'b10011:
      begin
        d2l_RESET_REQ_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_RESET_REQ_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_RESET_REQ_REG_r;
      end
    //  Register: RESET_ACK_REG     Address: 0x50     External: false
    5'b10100:
      begin
        d2l_RESET_ACK_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_RESET_ACK_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_RESET_ACK_REG_r;
      end
    //  Register: SYS_TICK_CONFIG_REG     Address: 0x54     External: false
    5'b10101:
      begin
        d2l_SYS_TICK_CONFIG_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_SYS_TICK_CONFIG_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_SYS_TICK_CONFIG_REG_r;
      end
    //  Register: SYS_RESET_AGGR_REG     Address: 0x58     External: false
    5'b10110:
      begin
        d2l_SYS_RESET_AGGR_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_SYS_RESET_AGGR_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_SYS_RESET_AGGR_REG_r;
      end
    endcase
  end

endmodule
