# =============================================================================
# Compile Design GLS
# =============================================================================
# Author  : Kalhan Koul
# Date    : February 7, 2021
# =============================================================================

name: compile_design_gls

# -----------------------------------------------------------------------------
# Inputs
# -----------------------------------------------------------------------------
inputs:
  

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------
commands:
  - bash run.sh


# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------

parameters:
  ARM_IP_DIR: undefined
  AHA_IP_DIR: undefined
  GATE_LEVEL_DIR: undefined
  CGRA_RD_WS: 1
  soc_only: undefined
  TLX_FWD_DATA_LO_WIDTH: undefined
  TLX_REV_DATA_LO_WIDTH: undefined
