//   Ordt 190617.01 autogenerated file
//   Input: tlx_ctrl.rdl
//   Parms: ./ordt/params.txt
//   Date: Thu May 07 11:38:21 PDT 2020
//

//
//---------- module AhaTlxCtrlAddrMap_jrdl_decode
//
module AhaTlxCtrlAddrMap_jrdl_decode
(
  clk,
  reset,
  h2d_pio_dec_address,
  h2d_pio_dec_write_data,
  h2d_pio_dec_write_enable,
  h2d_pio_dec_write,
  h2d_pio_dec_read,
  l2d_ID_REG_r,
  l2d_LANE_ENABLE_REG_r,
  l2d_LANE_IE_REG_r,
  l2d_LANE_START_REG_r,
  l2d_LANE_CLEAR_REG_r,
  l2d_LANE_INT_STATUS_REG_r,
  l2d_LANE_STATUS_REG_r,
  l2d_LANE0_SEQUENCE_REG_r,
  l2d_LANE1_SEQUENCE_REG_r,
  l2d_LANE2_SEQUENCE_REG_r,
  l2d_LANE3_SEQUENCE_REG_r,
  l2d_LANE4_SEQUENCE_REG_r,
  l2d_LANE5_SEQUENCE_REG_r,
  l2d_LANE6_SEQUENCE_REG_r,
  l2d_LANE7_SEQUENCE_REG_r,
  l2d_LANE8_SEQUENCE_REG_r,
  l2d_LANE9_SEQUENCE_REG_r,
  l2d_LANE0_LENGTH_REG_r,
  l2d_LANE1_LENGTH_REG_r,
  l2d_LANE2_LENGTH_REG_r,
  l2d_LANE3_LENGTH_REG_r,
  l2d_LANE4_LENGTH_REG_r,
  l2d_LANE5_LENGTH_REG_r,
  l2d_LANE6_LENGTH_REG_r,
  l2d_LANE7_LENGTH_REG_r,
  l2d_LANE8_LENGTH_REG_r,
  l2d_LANE9_LENGTH_REG_r,
  l2d_LANE0_MATCH_COUNT_REG_r,
  l2d_LANE1_MATCH_COUNT_REG_r,
  l2d_LANE2_MATCH_COUNT_REG_r,
  l2d_LANE3_MATCH_COUNT_REG_r,
  l2d_LANE4_MATCH_COUNT_REG_r,
  l2d_LANE5_MATCH_COUNT_REG_r,
  l2d_LANE6_MATCH_COUNT_REG_r,
  l2d_LANE7_MATCH_COUNT_REG_r,
  l2d_LANE8_MATCH_COUNT_REG_r,
  l2d_LANE9_MATCH_COUNT_REG_r,

  d2h_dec_pio_read_data,
  d2h_dec_pio_ack,
  d2h_dec_pio_nack,
  d2l_ID_REG_w,
  d2l_ID_REG_w_enable,
  d2l_ID_REG_we,
  d2l_ID_REG_re,
  d2l_LANE_ENABLE_REG_w,
  d2l_LANE_ENABLE_REG_w_enable,
  d2l_LANE_ENABLE_REG_we,
  d2l_LANE_ENABLE_REG_re,
  d2l_LANE_IE_REG_w,
  d2l_LANE_IE_REG_w_enable,
  d2l_LANE_IE_REG_we,
  d2l_LANE_IE_REG_re,
  d2l_LANE_START_REG_w,
  d2l_LANE_START_REG_w_enable,
  d2l_LANE_START_REG_we,
  d2l_LANE_START_REG_re,
  d2l_LANE_CLEAR_REG_w,
  d2l_LANE_CLEAR_REG_w_enable,
  d2l_LANE_CLEAR_REG_we,
  d2l_LANE_CLEAR_REG_re,
  d2l_LANE_INT_STATUS_REG_w,
  d2l_LANE_INT_STATUS_REG_w_enable,
  d2l_LANE_INT_STATUS_REG_we,
  d2l_LANE_INT_STATUS_REG_re,
  d2l_LANE_STATUS_REG_w,
  d2l_LANE_STATUS_REG_w_enable,
  d2l_LANE_STATUS_REG_we,
  d2l_LANE_STATUS_REG_re,
  d2l_LANE0_SEQUENCE_REG_w,
  d2l_LANE0_SEQUENCE_REG_w_enable,
  d2l_LANE0_SEQUENCE_REG_we,
  d2l_LANE0_SEQUENCE_REG_re,
  d2l_LANE1_SEQUENCE_REG_w,
  d2l_LANE1_SEQUENCE_REG_w_enable,
  d2l_LANE1_SEQUENCE_REG_we,
  d2l_LANE1_SEQUENCE_REG_re,
  d2l_LANE2_SEQUENCE_REG_w,
  d2l_LANE2_SEQUENCE_REG_w_enable,
  d2l_LANE2_SEQUENCE_REG_we,
  d2l_LANE2_SEQUENCE_REG_re,
  d2l_LANE3_SEQUENCE_REG_w,
  d2l_LANE3_SEQUENCE_REG_w_enable,
  d2l_LANE3_SEQUENCE_REG_we,
  d2l_LANE3_SEQUENCE_REG_re,
  d2l_LANE4_SEQUENCE_REG_w,
  d2l_LANE4_SEQUENCE_REG_w_enable,
  d2l_LANE4_SEQUENCE_REG_we,
  d2l_LANE4_SEQUENCE_REG_re,
  d2l_LANE5_SEQUENCE_REG_w,
  d2l_LANE5_SEQUENCE_REG_w_enable,
  d2l_LANE5_SEQUENCE_REG_we,
  d2l_LANE5_SEQUENCE_REG_re,
  d2l_LANE6_SEQUENCE_REG_w,
  d2l_LANE6_SEQUENCE_REG_w_enable,
  d2l_LANE6_SEQUENCE_REG_we,
  d2l_LANE6_SEQUENCE_REG_re,
  d2l_LANE7_SEQUENCE_REG_w,
  d2l_LANE7_SEQUENCE_REG_w_enable,
  d2l_LANE7_SEQUENCE_REG_we,
  d2l_LANE7_SEQUENCE_REG_re,
  d2l_LANE8_SEQUENCE_REG_w,
  d2l_LANE8_SEQUENCE_REG_w_enable,
  d2l_LANE8_SEQUENCE_REG_we,
  d2l_LANE8_SEQUENCE_REG_re,
  d2l_LANE9_SEQUENCE_REG_w,
  d2l_LANE9_SEQUENCE_REG_w_enable,
  d2l_LANE9_SEQUENCE_REG_we,
  d2l_LANE9_SEQUENCE_REG_re,
  d2l_LANE0_LENGTH_REG_w,
  d2l_LANE0_LENGTH_REG_w_enable,
  d2l_LANE0_LENGTH_REG_we,
  d2l_LANE0_LENGTH_REG_re,
  d2l_LANE1_LENGTH_REG_w,
  d2l_LANE1_LENGTH_REG_w_enable,
  d2l_LANE1_LENGTH_REG_we,
  d2l_LANE1_LENGTH_REG_re,
  d2l_LANE2_LENGTH_REG_w,
  d2l_LANE2_LENGTH_REG_w_enable,
  d2l_LANE2_LENGTH_REG_we,
  d2l_LANE2_LENGTH_REG_re,
  d2l_LANE3_LENGTH_REG_w,
  d2l_LANE3_LENGTH_REG_w_enable,
  d2l_LANE3_LENGTH_REG_we,
  d2l_LANE3_LENGTH_REG_re,
  d2l_LANE4_LENGTH_REG_w,
  d2l_LANE4_LENGTH_REG_w_enable,
  d2l_LANE4_LENGTH_REG_we,
  d2l_LANE4_LENGTH_REG_re,
  d2l_LANE5_LENGTH_REG_w,
  d2l_LANE5_LENGTH_REG_w_enable,
  d2l_LANE5_LENGTH_REG_we,
  d2l_LANE5_LENGTH_REG_re,
  d2l_LANE6_LENGTH_REG_w,
  d2l_LANE6_LENGTH_REG_w_enable,
  d2l_LANE6_LENGTH_REG_we,
  d2l_LANE6_LENGTH_REG_re,
  d2l_LANE7_LENGTH_REG_w,
  d2l_LANE7_LENGTH_REG_w_enable,
  d2l_LANE7_LENGTH_REG_we,
  d2l_LANE7_LENGTH_REG_re,
  d2l_LANE8_LENGTH_REG_w,
  d2l_LANE8_LENGTH_REG_w_enable,
  d2l_LANE8_LENGTH_REG_we,
  d2l_LANE8_LENGTH_REG_re,
  d2l_LANE9_LENGTH_REG_w,
  d2l_LANE9_LENGTH_REG_w_enable,
  d2l_LANE9_LENGTH_REG_we,
  d2l_LANE9_LENGTH_REG_re,
  d2l_LANE0_MATCH_COUNT_REG_w,
  d2l_LANE0_MATCH_COUNT_REG_w_enable,
  d2l_LANE0_MATCH_COUNT_REG_we,
  d2l_LANE0_MATCH_COUNT_REG_re,
  d2l_LANE1_MATCH_COUNT_REG_w,
  d2l_LANE1_MATCH_COUNT_REG_w_enable,
  d2l_LANE1_MATCH_COUNT_REG_we,
  d2l_LANE1_MATCH_COUNT_REG_re,
  d2l_LANE2_MATCH_COUNT_REG_w,
  d2l_LANE2_MATCH_COUNT_REG_w_enable,
  d2l_LANE2_MATCH_COUNT_REG_we,
  d2l_LANE2_MATCH_COUNT_REG_re,
  d2l_LANE3_MATCH_COUNT_REG_w,
  d2l_LANE3_MATCH_COUNT_REG_w_enable,
  d2l_LANE3_MATCH_COUNT_REG_we,
  d2l_LANE3_MATCH_COUNT_REG_re,
  d2l_LANE4_MATCH_COUNT_REG_w,
  d2l_LANE4_MATCH_COUNT_REG_w_enable,
  d2l_LANE4_MATCH_COUNT_REG_we,
  d2l_LANE4_MATCH_COUNT_REG_re,
  d2l_LANE5_MATCH_COUNT_REG_w,
  d2l_LANE5_MATCH_COUNT_REG_w_enable,
  d2l_LANE5_MATCH_COUNT_REG_we,
  d2l_LANE5_MATCH_COUNT_REG_re,
  d2l_LANE6_MATCH_COUNT_REG_w,
  d2l_LANE6_MATCH_COUNT_REG_w_enable,
  d2l_LANE6_MATCH_COUNT_REG_we,
  d2l_LANE6_MATCH_COUNT_REG_re,
  d2l_LANE7_MATCH_COUNT_REG_w,
  d2l_LANE7_MATCH_COUNT_REG_w_enable,
  d2l_LANE7_MATCH_COUNT_REG_we,
  d2l_LANE7_MATCH_COUNT_REG_re,
  d2l_LANE8_MATCH_COUNT_REG_w,
  d2l_LANE8_MATCH_COUNT_REG_w_enable,
  d2l_LANE8_MATCH_COUNT_REG_we,
  d2l_LANE8_MATCH_COUNT_REG_re,
  d2l_LANE9_MATCH_COUNT_REG_w,
  d2l_LANE9_MATCH_COUNT_REG_w_enable,
  d2l_LANE9_MATCH_COUNT_REG_we,
  d2l_LANE9_MATCH_COUNT_REG_re );

  //------- inputs
  input    clk;
  input    reset;
  input     [7:2] h2d_pio_dec_address;
  input     [31:0] h2d_pio_dec_write_data;
  input     [3:0] h2d_pio_dec_write_enable;
  input    h2d_pio_dec_write;
  input    h2d_pio_dec_read;
  input     [31:0] l2d_ID_REG_r;
  input     [31:0] l2d_LANE_ENABLE_REG_r;
  input     [31:0] l2d_LANE_IE_REG_r;
  input     [31:0] l2d_LANE_START_REG_r;
  input     [31:0] l2d_LANE_CLEAR_REG_r;
  input     [31:0] l2d_LANE_INT_STATUS_REG_r;
  input     [31:0] l2d_LANE_STATUS_REG_r;
  input     [31:0] l2d_LANE0_SEQUENCE_REG_r;
  input     [31:0] l2d_LANE1_SEQUENCE_REG_r;
  input     [31:0] l2d_LANE2_SEQUENCE_REG_r;
  input     [31:0] l2d_LANE3_SEQUENCE_REG_r;
  input     [31:0] l2d_LANE4_SEQUENCE_REG_r;
  input     [31:0] l2d_LANE5_SEQUENCE_REG_r;
  input     [31:0] l2d_LANE6_SEQUENCE_REG_r;
  input     [31:0] l2d_LANE7_SEQUENCE_REG_r;
  input     [31:0] l2d_LANE8_SEQUENCE_REG_r;
  input     [31:0] l2d_LANE9_SEQUENCE_REG_r;
  input     [31:0] l2d_LANE0_LENGTH_REG_r;
  input     [31:0] l2d_LANE1_LENGTH_REG_r;
  input     [31:0] l2d_LANE2_LENGTH_REG_r;
  input     [31:0] l2d_LANE3_LENGTH_REG_r;
  input     [31:0] l2d_LANE4_LENGTH_REG_r;
  input     [31:0] l2d_LANE5_LENGTH_REG_r;
  input     [31:0] l2d_LANE6_LENGTH_REG_r;
  input     [31:0] l2d_LANE7_LENGTH_REG_r;
  input     [31:0] l2d_LANE8_LENGTH_REG_r;
  input     [31:0] l2d_LANE9_LENGTH_REG_r;
  input     [31:0] l2d_LANE0_MATCH_COUNT_REG_r;
  input     [31:0] l2d_LANE1_MATCH_COUNT_REG_r;
  input     [31:0] l2d_LANE2_MATCH_COUNT_REG_r;
  input     [31:0] l2d_LANE3_MATCH_COUNT_REG_r;
  input     [31:0] l2d_LANE4_MATCH_COUNT_REG_r;
  input     [31:0] l2d_LANE5_MATCH_COUNT_REG_r;
  input     [31:0] l2d_LANE6_MATCH_COUNT_REG_r;
  input     [31:0] l2d_LANE7_MATCH_COUNT_REG_r;
  input     [31:0] l2d_LANE8_MATCH_COUNT_REG_r;
  input     [31:0] l2d_LANE9_MATCH_COUNT_REG_r;

  //------- outputs
  output     [31:0] d2h_dec_pio_read_data;
  output    d2h_dec_pio_ack;
  output    d2h_dec_pio_nack;
  output     [31:0] d2l_ID_REG_w;
  output     [31:0] d2l_ID_REG_w_enable;
  output    d2l_ID_REG_we;
  output    d2l_ID_REG_re;
  output     [31:0] d2l_LANE_ENABLE_REG_w;
  output     [31:0] d2l_LANE_ENABLE_REG_w_enable;
  output    d2l_LANE_ENABLE_REG_we;
  output    d2l_LANE_ENABLE_REG_re;
  output     [31:0] d2l_LANE_IE_REG_w;
  output     [31:0] d2l_LANE_IE_REG_w_enable;
  output    d2l_LANE_IE_REG_we;
  output    d2l_LANE_IE_REG_re;
  output     [31:0] d2l_LANE_START_REG_w;
  output     [31:0] d2l_LANE_START_REG_w_enable;
  output    d2l_LANE_START_REG_we;
  output    d2l_LANE_START_REG_re;
  output     [31:0] d2l_LANE_CLEAR_REG_w;
  output     [31:0] d2l_LANE_CLEAR_REG_w_enable;
  output    d2l_LANE_CLEAR_REG_we;
  output    d2l_LANE_CLEAR_REG_re;
  output     [31:0] d2l_LANE_INT_STATUS_REG_w;
  output     [31:0] d2l_LANE_INT_STATUS_REG_w_enable;
  output    d2l_LANE_INT_STATUS_REG_we;
  output    d2l_LANE_INT_STATUS_REG_re;
  output     [31:0] d2l_LANE_STATUS_REG_w;
  output     [31:0] d2l_LANE_STATUS_REG_w_enable;
  output    d2l_LANE_STATUS_REG_we;
  output    d2l_LANE_STATUS_REG_re;
  output     [31:0] d2l_LANE0_SEQUENCE_REG_w;
  output     [31:0] d2l_LANE0_SEQUENCE_REG_w_enable;
  output    d2l_LANE0_SEQUENCE_REG_we;
  output    d2l_LANE0_SEQUENCE_REG_re;
  output     [31:0] d2l_LANE1_SEQUENCE_REG_w;
  output     [31:0] d2l_LANE1_SEQUENCE_REG_w_enable;
  output    d2l_LANE1_SEQUENCE_REG_we;
  output    d2l_LANE1_SEQUENCE_REG_re;
  output     [31:0] d2l_LANE2_SEQUENCE_REG_w;
  output     [31:0] d2l_LANE2_SEQUENCE_REG_w_enable;
  output    d2l_LANE2_SEQUENCE_REG_we;
  output    d2l_LANE2_SEQUENCE_REG_re;
  output     [31:0] d2l_LANE3_SEQUENCE_REG_w;
  output     [31:0] d2l_LANE3_SEQUENCE_REG_w_enable;
  output    d2l_LANE3_SEQUENCE_REG_we;
  output    d2l_LANE3_SEQUENCE_REG_re;
  output     [31:0] d2l_LANE4_SEQUENCE_REG_w;
  output     [31:0] d2l_LANE4_SEQUENCE_REG_w_enable;
  output    d2l_LANE4_SEQUENCE_REG_we;
  output    d2l_LANE4_SEQUENCE_REG_re;
  output     [31:0] d2l_LANE5_SEQUENCE_REG_w;
  output     [31:0] d2l_LANE5_SEQUENCE_REG_w_enable;
  output    d2l_LANE5_SEQUENCE_REG_we;
  output    d2l_LANE5_SEQUENCE_REG_re;
  output     [31:0] d2l_LANE6_SEQUENCE_REG_w;
  output     [31:0] d2l_LANE6_SEQUENCE_REG_w_enable;
  output    d2l_LANE6_SEQUENCE_REG_we;
  output    d2l_LANE6_SEQUENCE_REG_re;
  output     [31:0] d2l_LANE7_SEQUENCE_REG_w;
  output     [31:0] d2l_LANE7_SEQUENCE_REG_w_enable;
  output    d2l_LANE7_SEQUENCE_REG_we;
  output    d2l_LANE7_SEQUENCE_REG_re;
  output     [31:0] d2l_LANE8_SEQUENCE_REG_w;
  output     [31:0] d2l_LANE8_SEQUENCE_REG_w_enable;
  output    d2l_LANE8_SEQUENCE_REG_we;
  output    d2l_LANE8_SEQUENCE_REG_re;
  output     [31:0] d2l_LANE9_SEQUENCE_REG_w;
  output     [31:0] d2l_LANE9_SEQUENCE_REG_w_enable;
  output    d2l_LANE9_SEQUENCE_REG_we;
  output    d2l_LANE9_SEQUENCE_REG_re;
  output     [31:0] d2l_LANE0_LENGTH_REG_w;
  output     [31:0] d2l_LANE0_LENGTH_REG_w_enable;
  output    d2l_LANE0_LENGTH_REG_we;
  output    d2l_LANE0_LENGTH_REG_re;
  output     [31:0] d2l_LANE1_LENGTH_REG_w;
  output     [31:0] d2l_LANE1_LENGTH_REG_w_enable;
  output    d2l_LANE1_LENGTH_REG_we;
  output    d2l_LANE1_LENGTH_REG_re;
  output     [31:0] d2l_LANE2_LENGTH_REG_w;
  output     [31:0] d2l_LANE2_LENGTH_REG_w_enable;
  output    d2l_LANE2_LENGTH_REG_we;
  output    d2l_LANE2_LENGTH_REG_re;
  output     [31:0] d2l_LANE3_LENGTH_REG_w;
  output     [31:0] d2l_LANE3_LENGTH_REG_w_enable;
  output    d2l_LANE3_LENGTH_REG_we;
  output    d2l_LANE3_LENGTH_REG_re;
  output     [31:0] d2l_LANE4_LENGTH_REG_w;
  output     [31:0] d2l_LANE4_LENGTH_REG_w_enable;
  output    d2l_LANE4_LENGTH_REG_we;
  output    d2l_LANE4_LENGTH_REG_re;
  output     [31:0] d2l_LANE5_LENGTH_REG_w;
  output     [31:0] d2l_LANE5_LENGTH_REG_w_enable;
  output    d2l_LANE5_LENGTH_REG_we;
  output    d2l_LANE5_LENGTH_REG_re;
  output     [31:0] d2l_LANE6_LENGTH_REG_w;
  output     [31:0] d2l_LANE6_LENGTH_REG_w_enable;
  output    d2l_LANE6_LENGTH_REG_we;
  output    d2l_LANE6_LENGTH_REG_re;
  output     [31:0] d2l_LANE7_LENGTH_REG_w;
  output     [31:0] d2l_LANE7_LENGTH_REG_w_enable;
  output    d2l_LANE7_LENGTH_REG_we;
  output    d2l_LANE7_LENGTH_REG_re;
  output     [31:0] d2l_LANE8_LENGTH_REG_w;
  output     [31:0] d2l_LANE8_LENGTH_REG_w_enable;
  output    d2l_LANE8_LENGTH_REG_we;
  output    d2l_LANE8_LENGTH_REG_re;
  output     [31:0] d2l_LANE9_LENGTH_REG_w;
  output     [31:0] d2l_LANE9_LENGTH_REG_w_enable;
  output    d2l_LANE9_LENGTH_REG_we;
  output    d2l_LANE9_LENGTH_REG_re;
  output     [31:0] d2l_LANE0_MATCH_COUNT_REG_w;
  output     [31:0] d2l_LANE0_MATCH_COUNT_REG_w_enable;
  output    d2l_LANE0_MATCH_COUNT_REG_we;
  output    d2l_LANE0_MATCH_COUNT_REG_re;
  output     [31:0] d2l_LANE1_MATCH_COUNT_REG_w;
  output     [31:0] d2l_LANE1_MATCH_COUNT_REG_w_enable;
  output    d2l_LANE1_MATCH_COUNT_REG_we;
  output    d2l_LANE1_MATCH_COUNT_REG_re;
  output     [31:0] d2l_LANE2_MATCH_COUNT_REG_w;
  output     [31:0] d2l_LANE2_MATCH_COUNT_REG_w_enable;
  output    d2l_LANE2_MATCH_COUNT_REG_we;
  output    d2l_LANE2_MATCH_COUNT_REG_re;
  output     [31:0] d2l_LANE3_MATCH_COUNT_REG_w;
  output     [31:0] d2l_LANE3_MATCH_COUNT_REG_w_enable;
  output    d2l_LANE3_MATCH_COUNT_REG_we;
  output    d2l_LANE3_MATCH_COUNT_REG_re;
  output     [31:0] d2l_LANE4_MATCH_COUNT_REG_w;
  output     [31:0] d2l_LANE4_MATCH_COUNT_REG_w_enable;
  output    d2l_LANE4_MATCH_COUNT_REG_we;
  output    d2l_LANE4_MATCH_COUNT_REG_re;
  output     [31:0] d2l_LANE5_MATCH_COUNT_REG_w;
  output     [31:0] d2l_LANE5_MATCH_COUNT_REG_w_enable;
  output    d2l_LANE5_MATCH_COUNT_REG_we;
  output    d2l_LANE5_MATCH_COUNT_REG_re;
  output     [31:0] d2l_LANE6_MATCH_COUNT_REG_w;
  output     [31:0] d2l_LANE6_MATCH_COUNT_REG_w_enable;
  output    d2l_LANE6_MATCH_COUNT_REG_we;
  output    d2l_LANE6_MATCH_COUNT_REG_re;
  output     [31:0] d2l_LANE7_MATCH_COUNT_REG_w;
  output     [31:0] d2l_LANE7_MATCH_COUNT_REG_w_enable;
  output    d2l_LANE7_MATCH_COUNT_REG_we;
  output    d2l_LANE7_MATCH_COUNT_REG_re;
  output     [31:0] d2l_LANE8_MATCH_COUNT_REG_w;
  output     [31:0] d2l_LANE8_MATCH_COUNT_REG_w_enable;
  output    d2l_LANE8_MATCH_COUNT_REG_we;
  output    d2l_LANE8_MATCH_COUNT_REG_re;
  output     [31:0] d2l_LANE9_MATCH_COUNT_REG_w;
  output     [31:0] d2l_LANE9_MATCH_COUNT_REG_w_enable;
  output    d2l_LANE9_MATCH_COUNT_REG_we;
  output    d2l_LANE9_MATCH_COUNT_REG_re;


  //------- wire defines
  wire   [7:2] pio_dec_address;
  wire   [31:0] pio_dec_write_data;
  wire   [3:0] pio_dec_write_enable;
  wire  pio_dec_read;
  wire  pio_dec_write;

  //------- reg defines
  reg   [31:0] d2l_ID_REG_w;
  reg   [31:0] d2l_ID_REG_w_enable;
  reg  d2l_ID_REG_we;
  reg  d2l_ID_REG_re;
  reg   [31:0] d2l_LANE_ENABLE_REG_w;
  reg   [31:0] d2l_LANE_ENABLE_REG_w_enable;
  reg  d2l_LANE_ENABLE_REG_we;
  reg  d2l_LANE_ENABLE_REG_re;
  reg   [31:0] d2l_LANE_IE_REG_w;
  reg   [31:0] d2l_LANE_IE_REG_w_enable;
  reg  d2l_LANE_IE_REG_we;
  reg  d2l_LANE_IE_REG_re;
  reg   [31:0] d2l_LANE_START_REG_w;
  reg   [31:0] d2l_LANE_START_REG_w_enable;
  reg  d2l_LANE_START_REG_we;
  reg  d2l_LANE_START_REG_re;
  reg   [31:0] d2l_LANE_CLEAR_REG_w;
  reg   [31:0] d2l_LANE_CLEAR_REG_w_enable;
  reg  d2l_LANE_CLEAR_REG_we;
  reg  d2l_LANE_CLEAR_REG_re;
  reg   [31:0] d2l_LANE_INT_STATUS_REG_w;
  reg   [31:0] d2l_LANE_INT_STATUS_REG_w_enable;
  reg  d2l_LANE_INT_STATUS_REG_we;
  reg  d2l_LANE_INT_STATUS_REG_re;
  reg   [31:0] d2l_LANE_STATUS_REG_w;
  reg   [31:0] d2l_LANE_STATUS_REG_w_enable;
  reg  d2l_LANE_STATUS_REG_we;
  reg  d2l_LANE_STATUS_REG_re;
  reg   [31:0] d2l_LANE0_SEQUENCE_REG_w;
  reg   [31:0] d2l_LANE0_SEQUENCE_REG_w_enable;
  reg  d2l_LANE0_SEQUENCE_REG_we;
  reg  d2l_LANE0_SEQUENCE_REG_re;
  reg   [31:0] d2l_LANE1_SEQUENCE_REG_w;
  reg   [31:0] d2l_LANE1_SEQUENCE_REG_w_enable;
  reg  d2l_LANE1_SEQUENCE_REG_we;
  reg  d2l_LANE1_SEQUENCE_REG_re;
  reg   [31:0] d2l_LANE2_SEQUENCE_REG_w;
  reg   [31:0] d2l_LANE2_SEQUENCE_REG_w_enable;
  reg  d2l_LANE2_SEQUENCE_REG_we;
  reg  d2l_LANE2_SEQUENCE_REG_re;
  reg   [31:0] d2l_LANE3_SEQUENCE_REG_w;
  reg   [31:0] d2l_LANE3_SEQUENCE_REG_w_enable;
  reg  d2l_LANE3_SEQUENCE_REG_we;
  reg  d2l_LANE3_SEQUENCE_REG_re;
  reg   [31:0] d2l_LANE4_SEQUENCE_REG_w;
  reg   [31:0] d2l_LANE4_SEQUENCE_REG_w_enable;
  reg  d2l_LANE4_SEQUENCE_REG_we;
  reg  d2l_LANE4_SEQUENCE_REG_re;
  reg   [31:0] d2l_LANE5_SEQUENCE_REG_w;
  reg   [31:0] d2l_LANE5_SEQUENCE_REG_w_enable;
  reg  d2l_LANE5_SEQUENCE_REG_we;
  reg  d2l_LANE5_SEQUENCE_REG_re;
  reg   [31:0] d2l_LANE6_SEQUENCE_REG_w;
  reg   [31:0] d2l_LANE6_SEQUENCE_REG_w_enable;
  reg  d2l_LANE6_SEQUENCE_REG_we;
  reg  d2l_LANE6_SEQUENCE_REG_re;
  reg   [31:0] d2l_LANE7_SEQUENCE_REG_w;
  reg   [31:0] d2l_LANE7_SEQUENCE_REG_w_enable;
  reg  d2l_LANE7_SEQUENCE_REG_we;
  reg  d2l_LANE7_SEQUENCE_REG_re;
  reg   [31:0] d2l_LANE8_SEQUENCE_REG_w;
  reg   [31:0] d2l_LANE8_SEQUENCE_REG_w_enable;
  reg  d2l_LANE8_SEQUENCE_REG_we;
  reg  d2l_LANE8_SEQUENCE_REG_re;
  reg   [31:0] d2l_LANE9_SEQUENCE_REG_w;
  reg   [31:0] d2l_LANE9_SEQUENCE_REG_w_enable;
  reg  d2l_LANE9_SEQUENCE_REG_we;
  reg  d2l_LANE9_SEQUENCE_REG_re;
  reg   [31:0] d2l_LANE0_LENGTH_REG_w;
  reg   [31:0] d2l_LANE0_LENGTH_REG_w_enable;
  reg  d2l_LANE0_LENGTH_REG_we;
  reg  d2l_LANE0_LENGTH_REG_re;
  reg   [31:0] d2l_LANE1_LENGTH_REG_w;
  reg   [31:0] d2l_LANE1_LENGTH_REG_w_enable;
  reg  d2l_LANE1_LENGTH_REG_we;
  reg  d2l_LANE1_LENGTH_REG_re;
  reg   [31:0] d2l_LANE2_LENGTH_REG_w;
  reg   [31:0] d2l_LANE2_LENGTH_REG_w_enable;
  reg  d2l_LANE2_LENGTH_REG_we;
  reg  d2l_LANE2_LENGTH_REG_re;
  reg   [31:0] d2l_LANE3_LENGTH_REG_w;
  reg   [31:0] d2l_LANE3_LENGTH_REG_w_enable;
  reg  d2l_LANE3_LENGTH_REG_we;
  reg  d2l_LANE3_LENGTH_REG_re;
  reg   [31:0] d2l_LANE4_LENGTH_REG_w;
  reg   [31:0] d2l_LANE4_LENGTH_REG_w_enable;
  reg  d2l_LANE4_LENGTH_REG_we;
  reg  d2l_LANE4_LENGTH_REG_re;
  reg   [31:0] d2l_LANE5_LENGTH_REG_w;
  reg   [31:0] d2l_LANE5_LENGTH_REG_w_enable;
  reg  d2l_LANE5_LENGTH_REG_we;
  reg  d2l_LANE5_LENGTH_REG_re;
  reg   [31:0] d2l_LANE6_LENGTH_REG_w;
  reg   [31:0] d2l_LANE6_LENGTH_REG_w_enable;
  reg  d2l_LANE6_LENGTH_REG_we;
  reg  d2l_LANE6_LENGTH_REG_re;
  reg   [31:0] d2l_LANE7_LENGTH_REG_w;
  reg   [31:0] d2l_LANE7_LENGTH_REG_w_enable;
  reg  d2l_LANE7_LENGTH_REG_we;
  reg  d2l_LANE7_LENGTH_REG_re;
  reg   [31:0] d2l_LANE8_LENGTH_REG_w;
  reg   [31:0] d2l_LANE8_LENGTH_REG_w_enable;
  reg  d2l_LANE8_LENGTH_REG_we;
  reg  d2l_LANE8_LENGTH_REG_re;
  reg   [31:0] d2l_LANE9_LENGTH_REG_w;
  reg   [31:0] d2l_LANE9_LENGTH_REG_w_enable;
  reg  d2l_LANE9_LENGTH_REG_we;
  reg  d2l_LANE9_LENGTH_REG_re;
  reg   [31:0] d2l_LANE0_MATCH_COUNT_REG_w;
  reg   [31:0] d2l_LANE0_MATCH_COUNT_REG_w_enable;
  reg  d2l_LANE0_MATCH_COUNT_REG_we;
  reg  d2l_LANE0_MATCH_COUNT_REG_re;
  reg   [31:0] d2l_LANE1_MATCH_COUNT_REG_w;
  reg   [31:0] d2l_LANE1_MATCH_COUNT_REG_w_enable;
  reg  d2l_LANE1_MATCH_COUNT_REG_we;
  reg  d2l_LANE1_MATCH_COUNT_REG_re;
  reg   [31:0] d2l_LANE2_MATCH_COUNT_REG_w;
  reg   [31:0] d2l_LANE2_MATCH_COUNT_REG_w_enable;
  reg  d2l_LANE2_MATCH_COUNT_REG_we;
  reg  d2l_LANE2_MATCH_COUNT_REG_re;
  reg   [31:0] d2l_LANE3_MATCH_COUNT_REG_w;
  reg   [31:0] d2l_LANE3_MATCH_COUNT_REG_w_enable;
  reg  d2l_LANE3_MATCH_COUNT_REG_we;
  reg  d2l_LANE3_MATCH_COUNT_REG_re;
  reg   [31:0] d2l_LANE4_MATCH_COUNT_REG_w;
  reg   [31:0] d2l_LANE4_MATCH_COUNT_REG_w_enable;
  reg  d2l_LANE4_MATCH_COUNT_REG_we;
  reg  d2l_LANE4_MATCH_COUNT_REG_re;
  reg   [31:0] d2l_LANE5_MATCH_COUNT_REG_w;
  reg   [31:0] d2l_LANE5_MATCH_COUNT_REG_w_enable;
  reg  d2l_LANE5_MATCH_COUNT_REG_we;
  reg  d2l_LANE5_MATCH_COUNT_REG_re;
  reg   [31:0] d2l_LANE6_MATCH_COUNT_REG_w;
  reg   [31:0] d2l_LANE6_MATCH_COUNT_REG_w_enable;
  reg  d2l_LANE6_MATCH_COUNT_REG_we;
  reg  d2l_LANE6_MATCH_COUNT_REG_re;
  reg   [31:0] d2l_LANE7_MATCH_COUNT_REG_w;
  reg   [31:0] d2l_LANE7_MATCH_COUNT_REG_w_enable;
  reg  d2l_LANE7_MATCH_COUNT_REG_we;
  reg  d2l_LANE7_MATCH_COUNT_REG_re;
  reg   [31:0] d2l_LANE8_MATCH_COUNT_REG_w;
  reg   [31:0] d2l_LANE8_MATCH_COUNT_REG_w_enable;
  reg  d2l_LANE8_MATCH_COUNT_REG_we;
  reg  d2l_LANE8_MATCH_COUNT_REG_re;
  reg   [31:0] d2l_LANE9_MATCH_COUNT_REG_w;
  reg   [31:0] d2l_LANE9_MATCH_COUNT_REG_w_enable;
  reg  d2l_LANE9_MATCH_COUNT_REG_we;
  reg  d2l_LANE9_MATCH_COUNT_REG_re;
  reg  pio_write_active;
  reg  pio_read_active;
  reg   [7:2] pio_dec_address_d1;
  reg   [31:0] pio_dec_write_data_d1;
  reg   [3:0] pio_dec_write_enable_d1;
  reg   [31:0] pio_dec_write_enable_full;
  reg   [31:0] dec_pio_read_data;
  reg   [31:0] dec_pio_read_data_d1;
  reg  dec_pio_ack;
  reg  dec_pio_nack;
  reg  dec_pio_ack_next;
  reg  dec_pio_nack_next;
  reg  pio_internal_ack;
  reg  pio_internal_nack;
  reg  pio_external_ack;
  reg  pio_external_nack;
  reg  pio_external_ack_next;
  reg  pio_external_nack_next;
  reg  pio_no_acks;
  reg  pio_activate_write;
  reg  pio_activate_read;
  reg   [31:0] dec_pio_read_data_next;
  reg  external_transaction_active;


  //------- assigns
  assign  pio_dec_address = h2d_pio_dec_address;
  assign  pio_dec_write_data = h2d_pio_dec_write_data;
  assign  pio_dec_write_enable = h2d_pio_dec_write_enable;
  assign  pio_dec_read = h2d_pio_dec_read;
  assign  pio_dec_write = h2d_pio_dec_write;
  assign  d2h_dec_pio_read_data = dec_pio_read_data;
  assign  d2h_dec_pio_ack = dec_pio_ack;
  assign  d2h_dec_pio_nack = dec_pio_nack;

  //------- combinatorial assigns for pio read data
  always @ (*) begin
    dec_pio_read_data = dec_pio_read_data_d1;
  end

  //------- reg assigns for pio read data
  always @ (posedge clk or posedge reset) begin
    if (reset) begin
      dec_pio_read_data_d1 <= #1  32'b0;
    end
    else begin
      dec_pio_read_data_d1 <= #1 dec_pio_read_data_next;
    end
  end

  //------- reg assigns for pio i/f
  always @ (posedge clk or posedge reset) begin
    if (reset) begin
      pio_write_active <= #1  1'b0;
      pio_read_active <= #1  1'b0;
    end
    else begin
      pio_write_active <= #1  pio_write_active ? pio_no_acks : pio_activate_write;
      pio_read_active <= #1  pio_read_active ? pio_no_acks : pio_activate_read;
      pio_dec_address_d1 <= #1   pio_dec_address;
      pio_dec_write_data_d1 <= #1  pio_dec_write_data;
      pio_dec_write_enable_d1 <= #1  pio_dec_write_enable;
    end
  end

  //------- combinatorial assigns for pio ack/nack
  always @ (*) begin
    pio_internal_nack = (pio_read_active | pio_write_active) & ~pio_internal_ack & ~external_transaction_active;
    dec_pio_ack_next = (pio_internal_ack | (pio_external_ack_next & external_transaction_active));
    dec_pio_nack_next = (pio_internal_nack | (pio_external_nack_next & external_transaction_active));
    pio_no_acks = ~(dec_pio_ack | dec_pio_nack | pio_external_ack | pio_external_nack);
    pio_activate_write = (pio_dec_write & ~(dec_pio_ack | dec_pio_nack));
    pio_activate_read = (pio_dec_read & ~(dec_pio_ack | dec_pio_nack));
  end

  //------- reg assigns for pio ack/nack
  always @ (posedge clk or posedge reset) begin
    if (reset) begin
      dec_pio_ack <= #1 1'b0;
      dec_pio_nack <= #1 1'b0;
      pio_external_ack <= #1  1'b0;
      pio_external_nack <= #1  1'b0;
    end
    else begin
      dec_pio_ack <= #1 dec_pio_ack ? 1'b0 : dec_pio_ack_next;
      dec_pio_nack <= #1 dec_pio_nack ? 1'b0 : dec_pio_nack_next;
      pio_external_ack <= #1 pio_external_ack_next;
      pio_external_nack <= #1 pio_external_nack_next;
    end
  end


  //------- address decode
  always @ (*) begin
    pio_internal_ack = 1'b0;
    external_transaction_active = 1'b0;
    pio_external_ack_next = 1'b0;
    pio_external_nack_next = 1'b0;
    dec_pio_read_data_next = 32'b0;
    pio_dec_write_enable_full = 32'd0;
    if (pio_dec_write_enable_d1[0]) pio_dec_write_enable_full [7:0]  = 8'hff;
    if (pio_dec_write_enable_d1[1]) pio_dec_write_enable_full [15:8]  = 8'hff;
    if (pio_dec_write_enable_d1[2]) pio_dec_write_enable_full [23:16]  = 8'hff;
    if (pio_dec_write_enable_d1[3]) pio_dec_write_enable_full [31:24]  = 8'hff;

    d2l_ID_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ID_REG_we = 1'b0;
    d2l_ID_REG_re = 1'b0;
    d2l_ID_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE_ENABLE_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE_ENABLE_REG_we = 1'b0;
    d2l_LANE_ENABLE_REG_re = 1'b0;
    d2l_LANE_ENABLE_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE_IE_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE_IE_REG_we = 1'b0;
    d2l_LANE_IE_REG_re = 1'b0;
    d2l_LANE_IE_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE_START_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE_START_REG_we = 1'b0;
    d2l_LANE_START_REG_re = 1'b0;
    d2l_LANE_START_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE_CLEAR_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE_CLEAR_REG_we = 1'b0;
    d2l_LANE_CLEAR_REG_re = 1'b0;
    d2l_LANE_CLEAR_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE_INT_STATUS_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE_INT_STATUS_REG_we = 1'b0;
    d2l_LANE_INT_STATUS_REG_re = 1'b0;
    d2l_LANE_INT_STATUS_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE_STATUS_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE_STATUS_REG_we = 1'b0;
    d2l_LANE_STATUS_REG_re = 1'b0;
    d2l_LANE_STATUS_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE0_SEQUENCE_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE0_SEQUENCE_REG_we = 1'b0;
    d2l_LANE0_SEQUENCE_REG_re = 1'b0;
    d2l_LANE0_SEQUENCE_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE1_SEQUENCE_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE1_SEQUENCE_REG_we = 1'b0;
    d2l_LANE1_SEQUENCE_REG_re = 1'b0;
    d2l_LANE1_SEQUENCE_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE2_SEQUENCE_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE2_SEQUENCE_REG_we = 1'b0;
    d2l_LANE2_SEQUENCE_REG_re = 1'b0;
    d2l_LANE2_SEQUENCE_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE3_SEQUENCE_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE3_SEQUENCE_REG_we = 1'b0;
    d2l_LANE3_SEQUENCE_REG_re = 1'b0;
    d2l_LANE3_SEQUENCE_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE4_SEQUENCE_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE4_SEQUENCE_REG_we = 1'b0;
    d2l_LANE4_SEQUENCE_REG_re = 1'b0;
    d2l_LANE4_SEQUENCE_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE5_SEQUENCE_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE5_SEQUENCE_REG_we = 1'b0;
    d2l_LANE5_SEQUENCE_REG_re = 1'b0;
    d2l_LANE5_SEQUENCE_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE6_SEQUENCE_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE6_SEQUENCE_REG_we = 1'b0;
    d2l_LANE6_SEQUENCE_REG_re = 1'b0;
    d2l_LANE6_SEQUENCE_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE7_SEQUENCE_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE7_SEQUENCE_REG_we = 1'b0;
    d2l_LANE7_SEQUENCE_REG_re = 1'b0;
    d2l_LANE7_SEQUENCE_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE8_SEQUENCE_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE8_SEQUENCE_REG_we = 1'b0;
    d2l_LANE8_SEQUENCE_REG_re = 1'b0;
    d2l_LANE8_SEQUENCE_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE9_SEQUENCE_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE9_SEQUENCE_REG_we = 1'b0;
    d2l_LANE9_SEQUENCE_REG_re = 1'b0;
    d2l_LANE9_SEQUENCE_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE0_LENGTH_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE0_LENGTH_REG_we = 1'b0;
    d2l_LANE0_LENGTH_REG_re = 1'b0;
    d2l_LANE0_LENGTH_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE1_LENGTH_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE1_LENGTH_REG_we = 1'b0;
    d2l_LANE1_LENGTH_REG_re = 1'b0;
    d2l_LANE1_LENGTH_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE2_LENGTH_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE2_LENGTH_REG_we = 1'b0;
    d2l_LANE2_LENGTH_REG_re = 1'b0;
    d2l_LANE2_LENGTH_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE3_LENGTH_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE3_LENGTH_REG_we = 1'b0;
    d2l_LANE3_LENGTH_REG_re = 1'b0;
    d2l_LANE3_LENGTH_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE4_LENGTH_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE4_LENGTH_REG_we = 1'b0;
    d2l_LANE4_LENGTH_REG_re = 1'b0;
    d2l_LANE4_LENGTH_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE5_LENGTH_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE5_LENGTH_REG_we = 1'b0;
    d2l_LANE5_LENGTH_REG_re = 1'b0;
    d2l_LANE5_LENGTH_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE6_LENGTH_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE6_LENGTH_REG_we = 1'b0;
    d2l_LANE6_LENGTH_REG_re = 1'b0;
    d2l_LANE6_LENGTH_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE7_LENGTH_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE7_LENGTH_REG_we = 1'b0;
    d2l_LANE7_LENGTH_REG_re = 1'b0;
    d2l_LANE7_LENGTH_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE8_LENGTH_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE8_LENGTH_REG_we = 1'b0;
    d2l_LANE8_LENGTH_REG_re = 1'b0;
    d2l_LANE8_LENGTH_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE9_LENGTH_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE9_LENGTH_REG_we = 1'b0;
    d2l_LANE9_LENGTH_REG_re = 1'b0;
    d2l_LANE9_LENGTH_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE0_MATCH_COUNT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE0_MATCH_COUNT_REG_we = 1'b0;
    d2l_LANE0_MATCH_COUNT_REG_re = 1'b0;
    d2l_LANE0_MATCH_COUNT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE1_MATCH_COUNT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE1_MATCH_COUNT_REG_we = 1'b0;
    d2l_LANE1_MATCH_COUNT_REG_re = 1'b0;
    d2l_LANE1_MATCH_COUNT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE2_MATCH_COUNT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE2_MATCH_COUNT_REG_we = 1'b0;
    d2l_LANE2_MATCH_COUNT_REG_re = 1'b0;
    d2l_LANE2_MATCH_COUNT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE3_MATCH_COUNT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE3_MATCH_COUNT_REG_we = 1'b0;
    d2l_LANE3_MATCH_COUNT_REG_re = 1'b0;
    d2l_LANE3_MATCH_COUNT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE4_MATCH_COUNT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE4_MATCH_COUNT_REG_we = 1'b0;
    d2l_LANE4_MATCH_COUNT_REG_re = 1'b0;
    d2l_LANE4_MATCH_COUNT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE5_MATCH_COUNT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE5_MATCH_COUNT_REG_we = 1'b0;
    d2l_LANE5_MATCH_COUNT_REG_re = 1'b0;
    d2l_LANE5_MATCH_COUNT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE6_MATCH_COUNT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE6_MATCH_COUNT_REG_we = 1'b0;
    d2l_LANE6_MATCH_COUNT_REG_re = 1'b0;
    d2l_LANE6_MATCH_COUNT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE7_MATCH_COUNT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE7_MATCH_COUNT_REG_we = 1'b0;
    d2l_LANE7_MATCH_COUNT_REG_re = 1'b0;
    d2l_LANE7_MATCH_COUNT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE8_MATCH_COUNT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE8_MATCH_COUNT_REG_we = 1'b0;
    d2l_LANE8_MATCH_COUNT_REG_re = 1'b0;
    d2l_LANE8_MATCH_COUNT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;
    d2l_LANE9_MATCH_COUNT_REG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_LANE9_MATCH_COUNT_REG_we = 1'b0;
    d2l_LANE9_MATCH_COUNT_REG_re = 1'b0;
    d2l_LANE9_MATCH_COUNT_REG_w_enable = pio_dec_write_enable_full  [31:0] ;

    casez(pio_dec_address_d1)
    //  Register: ID_REG     Address: 0x0     External: false
    6'b000000:
      begin
        d2l_ID_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_ID_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_ID_REG_r;
      end
    //  Register: LANE_ENABLE_REG     Address: 0x4     External: false
    6'b000001:
      begin
        d2l_LANE_ENABLE_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE_ENABLE_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE_ENABLE_REG_r;
      end
    //  Register: LANE_IE_REG     Address: 0x8     External: false
    6'b000010:
      begin
        d2l_LANE_IE_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE_IE_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE_IE_REG_r;
      end
    //  Register: LANE_START_REG     Address: 0xc     External: false
    6'b000011:
      begin
        d2l_LANE_START_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE_START_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE_START_REG_r;
      end
    //  Register: LANE_CLEAR_REG     Address: 0x10     External: false
    6'b000100:
      begin
        d2l_LANE_CLEAR_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE_CLEAR_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE_CLEAR_REG_r;
      end
    //  Register: LANE_INT_STATUS_REG     Address: 0x14     External: false
    6'b000101:
      begin
        d2l_LANE_INT_STATUS_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE_INT_STATUS_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE_INT_STATUS_REG_r;
      end
    //  Register: LANE_STATUS_REG     Address: 0x18     External: false
    6'b000110:
      begin
        d2l_LANE_STATUS_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE_STATUS_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE_STATUS_REG_r;
      end
    //  Register: LANE0_SEQUENCE_REG     Address: 0x1c     External: false
    6'b000111:
      begin
        d2l_LANE0_SEQUENCE_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE0_SEQUENCE_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE0_SEQUENCE_REG_r;
      end
    //  Register: LANE1_SEQUENCE_REG     Address: 0x20     External: false
    6'b001000:
      begin
        d2l_LANE1_SEQUENCE_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE1_SEQUENCE_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE1_SEQUENCE_REG_r;
      end
    //  Register: LANE2_SEQUENCE_REG     Address: 0x24     External: false
    6'b001001:
      begin
        d2l_LANE2_SEQUENCE_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE2_SEQUENCE_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE2_SEQUENCE_REG_r;
      end
    //  Register: LANE3_SEQUENCE_REG     Address: 0x28     External: false
    6'b001010:
      begin
        d2l_LANE3_SEQUENCE_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE3_SEQUENCE_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE3_SEQUENCE_REG_r;
      end
    //  Register: LANE4_SEQUENCE_REG     Address: 0x2c     External: false
    6'b001011:
      begin
        d2l_LANE4_SEQUENCE_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE4_SEQUENCE_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE4_SEQUENCE_REG_r;
      end
    //  Register: LANE5_SEQUENCE_REG     Address: 0x30     External: false
    6'b001100:
      begin
        d2l_LANE5_SEQUENCE_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE5_SEQUENCE_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE5_SEQUENCE_REG_r;
      end
    //  Register: LANE6_SEQUENCE_REG     Address: 0x34     External: false
    6'b001101:
      begin
        d2l_LANE6_SEQUENCE_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE6_SEQUENCE_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE6_SEQUENCE_REG_r;
      end
    //  Register: LANE7_SEQUENCE_REG     Address: 0x38     External: false
    6'b001110:
      begin
        d2l_LANE7_SEQUENCE_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE7_SEQUENCE_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE7_SEQUENCE_REG_r;
      end
    //  Register: LANE8_SEQUENCE_REG     Address: 0x3c     External: false
    6'b001111:
      begin
        d2l_LANE8_SEQUENCE_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE8_SEQUENCE_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE8_SEQUENCE_REG_r;
      end
    //  Register: LANE9_SEQUENCE_REG     Address: 0x40     External: false
    6'b010000:
      begin
        d2l_LANE9_SEQUENCE_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE9_SEQUENCE_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE9_SEQUENCE_REG_r;
      end
    //  Register: LANE0_LENGTH_REG     Address: 0x44     External: false
    6'b010001:
      begin
        d2l_LANE0_LENGTH_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE0_LENGTH_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE0_LENGTH_REG_r;
      end
    //  Register: LANE1_LENGTH_REG     Address: 0x48     External: false
    6'b010010:
      begin
        d2l_LANE1_LENGTH_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE1_LENGTH_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE1_LENGTH_REG_r;
      end
    //  Register: LANE2_LENGTH_REG     Address: 0x4c     External: false
    6'b010011:
      begin
        d2l_LANE2_LENGTH_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE2_LENGTH_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE2_LENGTH_REG_r;
      end
    //  Register: LANE3_LENGTH_REG     Address: 0x50     External: false
    6'b010100:
      begin
        d2l_LANE3_LENGTH_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE3_LENGTH_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE3_LENGTH_REG_r;
      end
    //  Register: LANE4_LENGTH_REG     Address: 0x54     External: false
    6'b010101:
      begin
        d2l_LANE4_LENGTH_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE4_LENGTH_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE4_LENGTH_REG_r;
      end
    //  Register: LANE5_LENGTH_REG     Address: 0x58     External: false
    6'b010110:
      begin
        d2l_LANE5_LENGTH_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE5_LENGTH_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE5_LENGTH_REG_r;
      end
    //  Register: LANE6_LENGTH_REG     Address: 0x5c     External: false
    6'b010111:
      begin
        d2l_LANE6_LENGTH_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE6_LENGTH_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE6_LENGTH_REG_r;
      end
    //  Register: LANE7_LENGTH_REG     Address: 0x60     External: false
    6'b011000:
      begin
        d2l_LANE7_LENGTH_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE7_LENGTH_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE7_LENGTH_REG_r;
      end
    //  Register: LANE8_LENGTH_REG     Address: 0x64     External: false
    6'b011001:
      begin
        d2l_LANE8_LENGTH_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE8_LENGTH_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE8_LENGTH_REG_r;
      end
    //  Register: LANE9_LENGTH_REG     Address: 0x68     External: false
    6'b011010:
      begin
        d2l_LANE9_LENGTH_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE9_LENGTH_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE9_LENGTH_REG_r;
      end
    //  Register: LANE0_MATCH_COUNT_REG     Address: 0x6c     External: false
    6'b011011:
      begin
        d2l_LANE0_MATCH_COUNT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE0_MATCH_COUNT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE0_MATCH_COUNT_REG_r;
      end
    //  Register: LANE1_MATCH_COUNT_REG     Address: 0x70     External: false
    6'b011100:
      begin
        d2l_LANE1_MATCH_COUNT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE1_MATCH_COUNT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE1_MATCH_COUNT_REG_r;
      end
    //  Register: LANE2_MATCH_COUNT_REG     Address: 0x74     External: false
    6'b011101:
      begin
        d2l_LANE2_MATCH_COUNT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE2_MATCH_COUNT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE2_MATCH_COUNT_REG_r;
      end
    //  Register: LANE3_MATCH_COUNT_REG     Address: 0x78     External: false
    6'b011110:
      begin
        d2l_LANE3_MATCH_COUNT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE3_MATCH_COUNT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE3_MATCH_COUNT_REG_r;
      end
    //  Register: LANE4_MATCH_COUNT_REG     Address: 0x7c     External: false
    6'b011111:
      begin
        d2l_LANE4_MATCH_COUNT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE4_MATCH_COUNT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE4_MATCH_COUNT_REG_r;
      end
    //  Register: LANE5_MATCH_COUNT_REG     Address: 0x80     External: false
    6'b100000:
      begin
        d2l_LANE5_MATCH_COUNT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE5_MATCH_COUNT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE5_MATCH_COUNT_REG_r;
      end
    //  Register: LANE6_MATCH_COUNT_REG     Address: 0x84     External: false
    6'b100001:
      begin
        d2l_LANE6_MATCH_COUNT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE6_MATCH_COUNT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE6_MATCH_COUNT_REG_r;
      end
    //  Register: LANE7_MATCH_COUNT_REG     Address: 0x88     External: false
    6'b100010:
      begin
        d2l_LANE7_MATCH_COUNT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE7_MATCH_COUNT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE7_MATCH_COUNT_REG_r;
      end
    //  Register: LANE8_MATCH_COUNT_REG     Address: 0x8c     External: false
    6'b100011:
      begin
        d2l_LANE8_MATCH_COUNT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE8_MATCH_COUNT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE8_MATCH_COUNT_REG_r;
      end
    //  Register: LANE9_MATCH_COUNT_REG     Address: 0x90     External: false
    6'b100100:
      begin
        d2l_LANE9_MATCH_COUNT_REG_we = pio_write_active & ~dec_pio_ack;
        d2l_LANE9_MATCH_COUNT_REG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_LANE9_MATCH_COUNT_REG_r;
      end
    endcase
  end

endmodule
